export const abi = [
  {
    inputs: [
      { internalType: "address", name: "_morphoBundler", type: "address" },
      { internalType: "address", name: "_p2pSigner", type: "address" },
      { internalType: "address", name: "_p2pTreasury", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AllowedCalldataChecker__DataTooShort", type: "error" },
  { inputs: [], name: "CalldataParser__InvalidSlice", type: "error" },
  {
    inputs: [
      { internalType: "bytes", name: "_actual", type: "bytes" },
      { internalType: "bytes", name: "_expected", type: "bytes" },
    ],
    name: "P2pLendingProxyFactory__CalldataEndsWithRuleViolated",
    type: "error",
  },
  {
    inputs: [
      { internalType: "bytes", name: "_actual", type: "bytes" },
      { internalType: "bytes", name: "_expected", type: "bytes" },
    ],
    name: "P2pLendingProxyFactory__CalldataStartsWithRuleViolated",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_calldataAfterSelectorLength", type: "uint256" },
      { internalType: "uint32", name: "_bytesCount", type: "uint32" },
    ],
    name: "P2pLendingProxyFactory__CalldataTooShortForEndsWithRule",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_calldataAfterSelectorLength", type: "uint256" },
      { internalType: "uint32", name: "_ruleIndex", type: "uint32" },
      { internalType: "uint32", name: "_bytesCount", type: "uint32" },
    ],
    name: "P2pLendingProxyFactory__CalldataTooShortForStartsWithRule",
    type: "error",
  },
  { inputs: [], name: "P2pLendingProxyFactory__InvalidP2pSignerSignature", type: "error" },
  {
    inputs: [
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
    ],
    name: "P2pLendingProxyFactory__NoCalldataAllowed",
    type: "error",
  },
  {
    inputs: [
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
    ],
    name: "P2pLendingProxyFactory__NoRulesDefined",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "_p2pSignerSigDeadline", type: "uint256" }],
    name: "P2pLendingProxyFactory__P2pSignerSignatureExpired",
    type: "error",
  },
  { inputs: [], name: "P2pLendingProxyFactory__ZeroP2pSignerAddress", type: "error" },
  {
    inputs: [{ internalType: "address", name: "_distributor", type: "address" }],
    name: "P2pMorphoProxyFactory__DistributorNotTrusted",
    type: "error",
  },
  { inputs: [], name: "P2pMorphoProxyFactory__IncorrectLengthOf_dataForMulticall", type: "error" },
  { inputs: [], name: "P2pMorphoProxyFactory__ZeroTrustedDistributorAddress", type: "error" },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__approve2_amount_ne_permitSingleForP2pLendingProxy_amount",
    type: "error",
  },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__approve2_token_ne_permitSingleForP2pLendingProxy_token",
    type: "error",
  },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__erc4626Deposit_assets_ne_permitSingleForP2pLendingProxy_amount",
    type: "error",
  },
  { inputs: [], name: "P2pMorphoProxyFactory__erc4626Deposit_receiver_ne_proxy", type: "error" },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__erc4626Deposit_vault_asset_ne_permitSingleForP2pLendingProxy_token",
    type: "error",
  },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__transferFrom2_amount_ne_permitSingleForP2pLendingProxy_amount",
    type: "error",
  },
  {
    inputs: [],
    name: "P2pMorphoProxyFactory__transferFrom2_asset_ne_permitSingleForP2pLendingProxy_token",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "_p2pOperator", type: "address" }],
    name: "P2pOperator__InvalidP2pOperator",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "_account", type: "address" }],
    name: "P2pOperator__UnauthorizedAccount",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "enum P2pStructs.FunctionType",
        name: "_functionType",
        type: "uint8",
      },
      { indexed: true, internalType: "address", name: "_contract", type: "address" },
      { indexed: true, internalType: "bytes4", name: "_selector", type: "bytes4" },
    ],
    name: "P2pLendingProxyFactory__CalldataRulesRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "enum P2pStructs.FunctionType",
        name: "_functionType",
        type: "uint8",
      },
      { indexed: true, internalType: "address", name: "_contract", type: "address" },
      { indexed: true, internalType: "bytes4", name: "_selector", type: "bytes4" },
      {
        components: [
          { internalType: "enum P2pStructs.RuleType", name: "ruleType", type: "uint8" },
          { internalType: "uint32", name: "index", type: "uint32" },
          { internalType: "bytes", name: "allowedBytes", type: "bytes" },
        ],
        indexed: false,
        internalType: "struct P2pStructs.Rule[]",
        name: "_rules",
        type: "tuple[]",
      },
    ],
    name: "P2pLendingProxyFactory__CalldataRulesSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_client", type: "address" },
      { indexed: true, internalType: "uint96", name: "_clientBasisPoints", type: "uint96" },
    ],
    name: "P2pLendingProxyFactory__Deposited",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_previousP2pSigner", type: "address" },
      { indexed: true, internalType: "address", name: "_newP2pSigner", type: "address" },
    ],
    name: "P2pLendingProxyFactory__P2pSignerTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_trustedDistributor", type: "address" },
    ],
    name: "P2pMorphoProxyFactory__TrustedDistributorRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_newTrustedDistributor", type: "address" },
    ],
    name: "P2pMorphoProxyFactory__TrustedDistributorSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_previousP2pOperator", type: "address" },
      { indexed: true, internalType: "address", name: "_newP2pOperator", type: "address" },
    ],
    name: "P2pOperator2Step__P2pOperatorTransferStarted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_previousP2pOperator", type: "address" },
      { indexed: true, internalType: "address", name: "_newP2pOperator", type: "address" },
    ],
    name: "P2pOperator__P2pOperatorTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "acceptP2pOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_target", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
      { internalType: "bytes", name: "_calldataAfterSelector", type: "bytes" },
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
    ],
    name: "checkCalldata",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_p2pOperatorToCheck", type: "address" },
      { internalType: "bool", name: "_shouldCheckP2pOperator", type: "bool" },
      { internalType: "address", name: "_distributor", type: "address" },
    ],
    name: "checkMorphoUrdClaim",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_lendingProtocolAddress", type: "address" },
      { internalType: "bytes", name: "_lendingProtocolCalldata", type: "bytes" },
      {
        components: [
          {
            components: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint160", name: "amount", type: "uint160" },
              { internalType: "uint48", name: "expiration", type: "uint48" },
              { internalType: "uint48", name: "nonce", type: "uint48" },
            ],
            internalType: "struct IAllowanceTransfer.PermitDetails",
            name: "details",
            type: "tuple",
          },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "uint256", name: "sigDeadline", type: "uint256" },
        ],
        internalType: "struct IAllowanceTransfer.PermitSingle",
        name: "_permitSingleForP2pLendingProxy",
        type: "tuple",
      },
      { internalType: "bytes", name: "_permit2SignatureForP2pLendingProxy", type: "bytes" },
      { internalType: "uint96", name: "_clientBasisPoints", type: "uint96" },
      { internalType: "uint256", name: "_p2pSignerSigDeadline", type: "uint256" },
      { internalType: "bytes", name: "_p2pSignerSignature", type: "bytes" },
    ],
    name: "deposit",
    outputs: [{ internalType: "address", name: "p2pLendingProxyAddress", type: "address" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllProxies",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
      { internalType: "address", name: "_contract", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
    ],
    name: "getCalldataRules",
    outputs: [
      {
        components: [
          { internalType: "enum P2pStructs.RuleType", name: "ruleType", type: "uint8" },
          { internalType: "uint32", name: "index", type: "uint32" },
          { internalType: "bytes", name: "allowedBytes", type: "bytes" },
        ],
        internalType: "struct P2pStructs.Rule[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_client", type: "address" },
      { internalType: "uint96", name: "_clientBasisPoints", type: "uint96" },
      { internalType: "uint256", name: "_p2pSignerSigDeadline", type: "uint256" },
    ],
    name: "getHashForP2pSigner",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getP2pOperator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getP2pSigner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPendingP2pOperator",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint160", name: "amount", type: "uint160" },
              { internalType: "uint48", name: "expiration", type: "uint48" },
              { internalType: "uint48", name: "nonce", type: "uint48" },
            ],
            internalType: "struct IAllowanceTransfer.PermitDetails",
            name: "details",
            type: "tuple",
          },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "uint256", name: "sigDeadline", type: "uint256" },
        ],
        internalType: "struct IAllowanceTransfer.PermitSingle",
        name: "_permitSingle",
        type: "tuple",
      },
    ],
    name: "getPermit2HashTypedData",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "_dataHash", type: "bytes32" }],
    name: "getPermit2HashTypedData",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            components: [
              { internalType: "address", name: "token", type: "address" },
              { internalType: "uint160", name: "amount", type: "uint160" },
              { internalType: "uint48", name: "expiration", type: "uint48" },
              { internalType: "uint48", name: "nonce", type: "uint48" },
            ],
            internalType: "struct IAllowanceTransfer.PermitDetails",
            name: "details",
            type: "tuple",
          },
          { internalType: "address", name: "spender", type: "address" },
          { internalType: "uint256", name: "sigDeadline", type: "uint256" },
        ],
        internalType: "struct IAllowanceTransfer.PermitSingle",
        name: "_permitSingle",
        type: "tuple",
      },
    ],
    name: "getPermitHash",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getReferenceP2pLendingProxy",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_distributor", type: "address" }],
    name: "isTrustedDistributor",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_client", type: "address" },
      { internalType: "uint96", name: "_clientBasisPoints", type: "uint96" },
    ],
    name: "predictP2pLendingProxyAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
      { internalType: "address", name: "_contract", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
    ],
    name: "removeCalldataRules",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_trustedDistributor", type: "address" }],
    name: "removeTrustedDistributor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum P2pStructs.FunctionType", name: "_functionType", type: "uint8" },
      { internalType: "address", name: "_contract", type: "address" },
      { internalType: "bytes4", name: "_selector", type: "bytes4" },
      {
        components: [
          { internalType: "enum P2pStructs.RuleType", name: "ruleType", type: "uint8" },
          { internalType: "uint32", name: "index", type: "uint32" },
          { internalType: "bytes", name: "allowedBytes", type: "bytes" },
        ],
        internalType: "struct P2pStructs.Rule[]",
        name: "_rules",
        type: "tuple[]",
      },
    ],
    name: "setCalldataRules",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newTrustedDistributor", type: "address" }],
    name: "setTrustedDistributor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes4", name: "interfaceId", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newP2pOperator", type: "address" }],
    name: "transferP2pOperator",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_newP2pSigner", type: "address" }],
    name: "transferP2pSigner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
